apiVersion: skaffold/v4beta4
kind: Config
build:
  artifacts:
    - image: madvindi/auth
      context: auth
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: madvindi/client
      context: client
      sync:
        manual:
          - src: '**/*.js'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: madvindi/tickets
      context: tickets
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
    - image: madvindi/orders
      context: orders
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: madvindi/expiration
      context: expiration
      sync: 
        manual:
          - dest: .
            src: src/**/*.ts
      docker:
        dockerfile: Dockerfile
    - image: madvindi/payments
      context: payments
      sync: 
        manual:
          - dest: .
            src: src/**/*.ts
      docker:
        dockerfile: Dockerfile
  local:
    push: false
manifests:
  rawYaml:
    - ./infra/k8s/*.yaml
deploy:
  kubectl: {}