apiVersion: apps/v1
kind: Deployment 
metadata:
  name: nats-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
        - name: nats
          image: nats-streaming:0.17.0
          args:
           [
            "-p",
            "4222",
            "-m",
            "8222",
            "-hbi", # Heartbeat Interval, specifies the interval at which the NATS Streaming Server sends heartbeats to clients. The default value is 5 seconds
            "5s",
            "-hbt", # "Heartbeat Timeout" and specifies the timeout for heartbeats from clients. If the server does not receive a heartbeat from a client within this timeout, it assumes the client has disconnected. The default value is 5 seconds.
            "5s",
            "-hbf", # "Heartbeat Failures" and specifies the number of consecutive heartbeat failures tolerated before the server considers a client as disconnected. The default value is 2.
            "2",
            "-SD",
            "-cid",
            "ticketing"
          ]

---
apiVersion: v1
kind: Service 
metadata: 
  name: nats-srv
spec:
  selector:
    app: nats
  ports:
    - name: client
      protocol: TCP
      port: 4222
      targetPort: 4222
    - name: monitoring
      protocol: TCP
      port: 8222
      targetPort: 8222